[[redirects]]
  from = "http://developer.helium.com/*"
  to = "http://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://developer.helium.com/*"
  to = "https://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/light-hotspots/guides/*"
  to = "/mine-hnt/data-only-guides/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/5g-on-helium/5g-poc"
  to = "/5g-on-helium/mobile-poc"
  status = 301
  force = true
[[redirects]]
  from = "/5g-on-helium/mining-5g"
  to = "/5g-on-helium/mobile-poc"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/app-wallet"
  to = "/mine-hnt/helium-hotspot-app"
  status = 301
  force = true
[[redirects]]
  from = "/hotspot-makers/maker-apps"
  to = "/hotspot-makers/hotspot-makers"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/policies"
  to = "/faq/terms"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/policies/terms"
  to = "/faq/terms"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/policies/privacy"
  to = "/faq/privacy"
  status = 301
  force = true
[[redirects]]
  from = "/solana/oracle-data"
  to = "/oracles/oracle-data"
  status = 301
  force = true
[[redirects]]
  from = "/solana/migration/hotspot-owner"
  to = "/solana/migration/hotspot-operator"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/helium-token"
  to = "/helium-tokens/hnt"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/open-lns"
  to = "/lorawan-on-helium/open-lns"
  status = 301
  force = true
[[redirects]]
  from = "/hotspot-makers/original-helium-hotspot"
  to = "/mine-hnt/helium-hotspot-app"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/twelve-words"
  to = "/wallets/wallet-seed-phrase"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/twenty-four-words"
  to = "/wallets/wallet-seed-phrase"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/oracles"
  to = "/oracles/price-oracles"
  status = 301
  force = true
[[redirects]]
  from = "/mine-hnt/validators/validators-and-voting-power"
  to = "/vote-escrow/voting-power"
  status = 301
  force = true
[[redirects]]
  from = "/validators/*"
  to = "/solana/migration/validator-operator"
  status = 301
  force = true
[[redirects]]
  from = "/iot"
  to = "/lorawan-on-helium"
  status = 301
  force = true
[[redirects]]
  from = "/mobile"
  to = "/5g-on-helium"
  status = 301
  force = true
[[redirects]]
  from = "/hotspot-makers/maker-apps"
  to = "/hotspot-makers"
  status = 301
  force = true
[build.environment]
  YARN_VERSION = "1.22.19"
  NODE_VERSION = "16.15.1"