[[redirects]]
  from = "http://developer.helium.com/*"
  to = "http://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://developer.helium.com/*"
  to = "https://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/helium-tokens/*"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/tokens"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/ledger"
  to = "/wallets/ledger-wallet"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/app-wallet/transaction-failures/"
  to = "/wallets/helium-wallet-app"
  status = 301
  force = true
[[redirects]]
  from = "/hotspot-makers/iot/data-only-hotspots"
  to = "/iot/data-only-hotspots"
  status = 301
  force = true
[[redirects]]
  from = "/mine-hnt/data-only-hotspots"
  to = "/iot/data-only-hotspots"
  status = 301
  force = true
[[redirects]]
  from = "/data-credit"
  to = "/tokens/data-credit"
  status = 301
  force = true
[[redirects]]
  from = "/data-credit-portal"
  to = "/tokens/data-credit-portal"
  status = 301
  force = true
[[redirects]]
  from = "/helium-tokens/hnt"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/hnt-token"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/helium-token"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/hnt-token"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/iot/run-a-lns"
  to = "/iot/run-an-lns"
  status = 301
  force = true
[[redirects]]
  from = "/iot/buy-an-oui"
  to = "/iot/run-an-lns/buy-an-oui"
  status = 301
  force = true
[[redirects]]
  from = "/iot/open-lns"
  to = "/iot/lorawan-network-servers"
  status = 301
  force = true
[[redirects]]
  from = "/console/hosting-providers"
  to = "/iot/find-a-lns-provider"
  status = 301
  force = true
[[redirects]]
  from = "/find-a-lns-provider"
  to = "/iot/find-a-lns-provider"
  status = 301
  force = true
[[redirects]]
  from = "/solana/migration/wallet-user"
  to = "/wallets/l1-migrate"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-mobile"
  to = "/mobile/helium-plus-mobile"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-aruba"
  to = "/mobile/helium-plus-aruba"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-fortinet"
  to = "/mobile/helium-plus-fortinet"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-juniper-mist"
  to = "/mobile/helium-plus-juniper-mist"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-meraki"
  to = "/mobile/helium-plus-meraki"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-mikrotik"
  to = "/mobile/helium-plus-mikrotik"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-ruckus"
  to = "/mobile/helium-plus-ruckus"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-ubiquiti"
  to = "/mobile/helium-plus-ubiquiti"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-generic"
  to = "/mobile/helium-plus-generic"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-onboarding"
  to = "/mobile/helium-plus-onboarding"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-radsecproxy"
  to = "/mobile/helium-plus-radsecproxy"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-cambium-cnmaestro"
  to = "/mobile/helium-plus-cambium-cnmaestro"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-Cisco-WLC-9800"
  to = "/mobile/helium-plus-Cisco-WLC-9800"
  status = 301
  force = true
[[redirects]]
  from = "/mobile/data-only-Cisco-WLC-5520"
  to = "/mobile/helium-plus-Cisco-WLC-5520"
  status = 301
  force = true
[[redirects]]
  from = "/iot/coverage-mapping"
  to = "/network-iot"
  status = 301
  force = true
[[redirects]]
  from = "/api/blockchain/introduction/"
  to = "/network-data/legacy-blockchain-data"
  status = 301
  force = true
[[redirects]]
  from = "/hotspot-makers/"
  to = "/network-iot/hotspots-iot/data-only-hotspots"
  status = 301
  force = true
[[redirects]]
  from = "/troubleshooting/network-troubleshooting/"
  to = "https://support.hellohelium.com/"
  status = 301
  force = true
[[redirects]]
  from = "/troubleshooting/replace-sd-card/"
  to = "https://support.hellohelium.com/"
  status = 301
  force = true
[[redirects]]
  from = "/iot/denylist"
  to = "/network-iot"
  status = 301
  force = true
[[redirects]]
  from = "/iot/lorawan-region-plans/"
  to = "/network-iot"
  status = 301
  force = true
[[redirects]]
  from = "/console/integrations/json-schema"
  to = "/network-iot/lorawan-network-servers"
  status = 301
  force = true
[[redirects]]
  from = "/tokens/mobile-token/"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/app-wallet/transfer-hotspot/"
  to = "/wallets/helium-wallet-app"
  status = 301
  force = true
[[redirects]]
  from = "/devblog/*"
  to = "/home"
  status = 301
  force = true
[[redirects]]
  from = "/iot/lorawan-region-plans"
  to = "/network-iot"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/mining/"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/iot/lorawan-frequency-plans"
  to = "/network-iot"
  status = 301
  force = true
[[redirects]]
  from = "/console"
  to = "/network-iot/lorawan-network-servers"
  status = 301
  force = true
[[redirects]]
  from = "/faq/helium-network/"
  to = "/home"
  status = 301
  force = true
[[redirects]]
  from = "/iot/coverage-mapping/"
  to = "/network-iot"
  status = 301
  force = true
[build.environment]
  YARN_VERSION = "1.22.21"
  NODE_VERSION = "20.19.5"