[[redirects]]
  from = "http://developer.helium.com/*"
  to = "http://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://developer.helium.com/*"
  to = "https://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/helium-tokens/*"
  to = "/tokens/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/tokens"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/sol-token"
  to = "/tokens/sol-token"
  status = 301
  force = true
[[redirects]]
  from = "/api"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/api/blockchain/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/api/blockchain"
  to = "/oracles/oracle-data"
  status = 301
  force = true
[[redirects]]
  from = "/api/console"
  to = "/console/api"
  status = 301
  force = true
[[redirects]]
  from = "/archive/api"
  to = "/api/blockchian"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/ledger"
  to = "/wallets/ledger-wallet"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/app-wallet/transaction-failures/"
  to = "/wallets/helium-wallet-app"
  status = 301
  force = true
[[redirects]]
  from = "/hotspot-makers/iot/data-only-hotspots"
  to = "/iot/data-only-hotspots"
  status = 301
  force = true
[[redirects]]
  from = "/mine-hnt/data-only-hotspots"
  to = "/iot/data-only-hotspots"
  status = 301
  force = true
[[redirects]]
  from = "/data-credit"
  to = "/tokens/data-credit"
  status = 301
  force = true
[[redirects]]
  from = "/data-credit-portal"
  to = "/tokens/data-credit-portal"
  status = 301
  force = true
[[redirects]]
  from = "/helium-tokens/hnt"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/hnt-token"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/helium-token"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/hnt-token"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/proof-of-coverage"
  to = "/iot/proof-of-coverage"
  status = 301
  force = true
[[redirects]]
  from = "/iot-token"
  to = "/tokens/iot-token"
  status = 301
  force = true
[[redirects]]
  from = "/iot/crowdspot"
  to = "/iot/denylist"
  status = 301
  force = true
[[redirects]]
  from = "/network-iot/crowdspot"
  to = "/iot/denylist"
  status = 301
  force = true
[[redirects]]
  from = "/network-iot/iot-denylist-removals"
  to = "/iot/denylist"
  status = 301
  force = true
[[redirects]]
  from = "/iot/denylist-removals"
  to = "/iot/denylist"
  status = 301
  force = true
[[redirects]]
  from = "/mine-hnt/denylist-removals"
  to = "/iot/denylist"
  status = 301
  force = true
[[redirects]]
  from = "/mobile-token"
  to = "/tokens/mobile-token"
  status = 301
  force = true
[[redirects]]
  from = "/5g-on-helium/mobile-poc"
  to = "/mobile/proof-of-coverage"
  status = 301
  force = true
[[redirects]]
  from = "/mobile"
  to = "/mobile/5g-on-helium"
  status = 301
  force = true
[[redirects]]
  from = "/mine-hnt"
  to = "/tokens/mine-iot"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network"
  to = "/iot/devices"
  status = 301
  force = true
[[redirects]]
  from = "/iot/run-a-lns"
  to = "/iot/run-an-lns"
  status = 301
  force = true
[[redirects]]
  from = "/iot/buy-an-oui"
  to = "/iot/run-an-lns/buy-an-oui"
  status = 301
  force = true
[[redirects]]
  from = "/iot/open-lns"
  to = "/iot/lorawan-network-servers"
  status = 301
  force = true
[[redirects]]
  from = "/lorawan-on-helium/frequency-plans"
  to = "/iot/lorawan-frequency-plans"
  status = 301
  force = true
[[redirects]]
  from = "/console/hosting-providers"
  to = "/iot/find-a-lns-provider"
  status = 301
  force = true
[[redirects]]
  from = "/find-a-lns-provider"
  to = "/iot/find-a-lns-provider"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/coverage-mapping"
  to = "/iot/coverage-mapping"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/devices/*"
  to = "/iot/devices/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/console/*"
  to = "/console/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/faq/privacy"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/faq/terms"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/home/faqdocs-installation"
  to = "/faq/docs-installation"
  status = 301
  force = true
[[redirects]]
  from = "/governance/staking-with-realms"
  to = "/governance/staking-with-helium-vote"
  status = 301
  force = true
[build.environment]
  YARN_VERSION = "1.22.21"
  NODE_VERSION = "18.19.0"