[[redirects]]
  from = "http://developer.helium.com/*"
  to = "http://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://developer.helium.com/*"
  to = "https://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/helium-tokens/sol-token"
  to = "/tokens/sol-token"
  status = 301
  force = true
[[redirects]]
  from = "/api"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/api/blockchain/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/api/blockchain"
  to = "/oracles/oracle-data"
  status = 301
  force = true
[[redirects]]
  from = "/api/console"
  to = "/console/api"
  status = 301
  force = true
[[redirects]]
  from = "/archive/api"
  to = "/api/blockchian"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/ledger"
  to = "/wallets/ledger-wallet"
  status = 301
  force = true
[[redirects]]
  from = "/hotspot-makers/iot/data-only-hotspots"
  to = "/iot/data-only-hotspots"
  status = 301
  force = true
[[redirects]]
  from = "/data-credit"
  to = "/tokens/data-credit"
  status = 301
  force = true
[[redirects]]
  from = "/data-credit-portal"
  to = "/tokens/data-credit-portal"
  status = 301
  force = true
[[redirects]]
  from = "/hnt-token"
  to = "/tokens/hnt-token"
  status = 301
  force = true
[[redirects]]
  from = "/iot-token"
  to = "/tokens/iot-token"
  status = 301
  force = true
[[redirects]]
  from = "/mobile-token"
  to = "/tokens/mobile-token"
  status = 301
  force = true
[[redirects]]
  from = "/mine-hnt"
  to = "/tokens/mine-iot"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/devices/*"
  to = "/iot/devices/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/console/*"
  to = "/console/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/faq/privacy"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/faq/terms"
  to = "/"
  status = 301
  force = true
[build.environment]
  YARN_VERSION = "1.22.19"
  NODE_VERSION = "16.15.1"