[[redirects]]
  from = "http://developer.helium.com/*"
  to = "http://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://developer.helium.com/*"
  to = "https://docs.helium.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/light-hotspots/guides/*"
  to = "/mine-hnt/data-only-guides/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/5g-on-helium/5g-poc"
  to = "/5g-on-helium/mobile-poc"
  status = 301
  force = true
[[redirects]]
  from = "/5g-on-helium/mining-5g"
  to = "/5g-on-helium/mobile-poc"
  status = 301
  force = true
[[redirects]]
  from = "/wallets/app-wallet"
  to = "/mine-hnt/helium-hotspot-app"
  status = 301
  force = true
[[redirects]]
  from = "/mine-hnt/maker-apps"
  to = "/hotspot-makers/maker-apps"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/policies"
  to = "/faq/terms"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/policies/terms"
  to = "/faq/terms"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/policies/privacy"
  to = "/faq/privacy"
  status = 301
  force = true
[[redirects]]
  from = "/solana/oracle-data"
  to = "/oracles/oracle-data"
  status = 301
  force = true
[[redirects]]
  from = "/solana/migration/hotspot-owner"
  to = "/solana/migration/hotspot-operator"
  status = 301
  force = true
[[redirects]]
  from = "/blockchain/helium-token"
  to = "/helium-tokens/hnt"
  status = 301
  force = true
[[redirects]]
  from = "/use-the-network/open-lns"
  to = "/lorawan-on-helium/open-lns"
  status = 301
  force = true
[build.environment]
  YARN_VERSION = "1.22.19"
  NODE_VERSION = "16.15.1"